import 'package:flutter/material.dart';

import 'models.dart';

final sampleSchedule = <DaySchedule>[
  DaySchedule(
    date: DateTime.now(),
    tasks: [
      Task(
        title: 'Wake Up',
        subtitle: 'Hydrate and quick journaling',
        start: const TimeOfDay(hour: 6, minute: 30),
        end: const TimeOfDay(hour: 7, minute: 0),
        category: 'Mindful',
        color: const Color(0xFF6FFFE9),
        icon: Icons.self_improvement,
        isDone: false,
      ),
      Task(
        title: 'Morning Routine',
        subtitle: 'Stretch + plan the day',
        start: const TimeOfDay(hour: 7, minute: 15),
        end: const TimeOfDay(hour: 8, minute: 0),
        category: 'Routine',
        color: const Color(0xFF9E7AFF),
        icon: Icons.brightness_5_rounded,
        isDone: false,
      ),
      Task(
        title: 'Deep Work Sprint',
        subtitle: 'Project Nova UI build',
        start: const TimeOfDay(hour: 9, minute: 0),
        end: const TimeOfDay(hour: 11, minute: 0),
        category: 'Project',
        color: const Color(0xFFFF7A8A),
        icon: Icons.bolt,
        isDone: false,
      ),
      Task(
        title: 'Lunch + Walk',
        subtitle: 'Light lunch and sunlight',
        start: const TimeOfDay(hour: 12, minute: 30),
        end: const TimeOfDay(hour: 13, minute: 15),
        category: 'Health',
        color: const Color(0xFF7AE1FF),
        icon: Icons.local_florist,
        isDone: false,
      ),
      Task(
        title: 'Team Sync',
        subtitle: 'Project updates with the squad',
        start: const TimeOfDay(hour: 14, minute: 0),
        end: const TimeOfDay(hour: 14, minute: 45),
        category: 'Collab',
        color: const Color(0xFF61E294),
        icon: Icons.groups,
        isDone: false,
      ),
      Task(
        title: 'Gym Session',
        subtitle: 'Push day + conditioning',
        start: const TimeOfDay(hour: 18, minute: 0),
        end: const TimeOfDay(hour: 19, minute: 0),
        category: 'Fitness',
        color: const Color(0xFFFFC759),
        icon: Icons.fitness_center,
        isDone: false,
      ),
    ],
  ),
  DaySchedule(
    date: DateTime.now().add(const Duration(days: 1)),
    tasks: [
      Task(
        title: 'Morning Run',
        subtitle: '5k easy pace with music',
        start: const TimeOfDay(hour: 7, minute: 0),
        end: const TimeOfDay(hour: 7, minute: 40),
        category: 'Health',
        color: const Color(0xFF7EE6A1),
        icon: Icons.directions_run,
      ),
      Task(
        title: 'Design Review',
        subtitle: 'Feedback on goals dashboard',
        start: const TimeOfDay(hour: 10, minute: 0),
        end: const TimeOfDay(hour: 11, minute: 0),
        category: 'Project',
        color: const Color(0xFF7AE1FF),
        icon: Icons.design_services,
      ),
      Task(
        title: 'Deep Work',
        subtitle: 'Implement habit heatmap interactions',
        start: const TimeOfDay(hour: 13, minute: 0),
        end: const TimeOfDay(hour: 15, minute: 0),
        category: 'Build',
        color: const Color(0xFFB784FF),
        icon: Icons.code,
      ),
      Task(
        title: 'Evening Wind Down',
        subtitle: 'Cook + read 20 pages',
        start: const TimeOfDay(hour: 19, minute: 0),
        end: const TimeOfDay(hour: 20, minute: 0),
        category: 'Routine',
        color: const Color(0xFFFF9F6E),
        icon: Icons.self_improvement,
      ),
    ],
  ),
  DaySchedule(
    date: DateTime.now().add(const Duration(days: 2)),
    tasks: [
      Task(
        title: 'Focus Block',
        subtitle: 'Project Nova QA + bug fixes',
        start: const TimeOfDay(hour: 9, minute: 0),
        end: const TimeOfDay(hour: 11, minute: 30),
        category: 'Project',
        color: const Color(0xFFFF7A8A),
        icon: Icons.bug_report,
      ),
      Task(
        title: 'Lunch Outside',
        subtitle: 'Meet Sam for a quick bite',
        start: const TimeOfDay(hour: 12, minute: 30),
        end: const TimeOfDay(hour: 13, minute: 15),
        category: 'Social',
        color: const Color(0xFF61E294),
        icon: Icons.emoji_people,
      ),
      Task(
        title: 'Weekly Review',
        subtitle: 'Plan next sprint + adjust goals',
        start: const TimeOfDay(hour: 16, minute: 0),
        end: const TimeOfDay(hour: 17, minute: 0),
        category: 'Planning',
        color: const Color(0xFF6FFFE9),
        icon: Icons.event_note,
      ),
      Task(
        title: 'Stretch + Mobility',
        subtitle: '15 minutes before bed',
        start: const TimeOfDay(hour: 21, minute: 15),
        end: const TimeOfDay(hour: 21, minute: 35),
        category: 'Recovery',
        color: const Color(0xFFE7E167),
        icon: Icons.self_improvement,
      ),
    ],
  ),
];

final sampleHabits = <Habit>[
  Habit(
    id: 'h1',
    name: 'Weight Lifting',
    caption: '3x a week for strength',
    color: const Color(0xFFB784FF),
    icon: Icons.fitness_center,
    completions: List.generate(42, (i) => i % 3 != 0),
    completionCounts: List<int>.filled(365, 0),
    recurrenceDays: const [1, 3, 5],
    timesPerDay: 1,
  ),
  Habit(
    id: 'h2',
    name: 'Healthy Eating',
    caption: 'Cook at home or choose greens',
    color: const Color(0xFF7EE6A1),
    icon: Icons.restaurant,
    completions: List.generate(42, (i) => i % 5 != 1),
    completionCounts: List<int>.filled(365, 0),
    recurrenceDays: const [1, 2, 3, 4, 5],
    timesPerDay: 3,
  ),
  Habit(
    id: 'h3',
    name: 'Reading',
    caption: '15 minutes every night',
    color: const Color(0xFFFF9F6E),
    icon: Icons.menu_book,
    completions: List.generate(42, (i) => i % 4 != 2),
    completionCounts: List<int>.filled(365, 0),
    recurrenceDays: const [1, 2, 3, 4, 5, 6, 7],
    timesPerDay: 1,
  ),
  Habit(
    id: 'h4',
    name: 'Guitar',
    caption: 'Practice daily',
    color: const Color(0xFFE7E167),
    icon: Icons.music_note,
    completions: List.generate(42, (i) => i % 6 != 3),
    completionCounts: List<int>.filled(365, 0),
    recurrenceDays: const [2, 4, 6],
    timesPerDay: 1,
  ),
];

final sampleProjects = <Project>[
  Project(
    id: 'p1',
    name: 'Project Nova',
    description: 'Shipping onboarding revamp.',
    progress: 0.72,
    color: const Color(0xFF7AE1FF),
    weeklyBurndown: const [6, 5.4, 5, 4.2, 3.7, 3, 2.4],
  ),
  Project(
    id: 'p2',
    name: 'Habit Kit',
    description: 'Build the habit heatmap module.',
    progress: 0.58,
    color: const Color(0xFFB784FF),
    weeklyBurndown: const [7, 6.3, 6, 5.5, 4.8, 4, 3.5],
  ),
  Project(
    id: 'p3',
    name: 'Life Dashboard',
    description: 'Analytics + goals panel polish.',
    progress: 0.43,
    color: const Color(0xFF61E294),
    weeklyBurndown: const [5.5, 5.1, 4.9, 4.4, 4, 3.6, 3],
  ),
];

final sampleGoals = <Goal>[
  Goal(
    id: 'g1',
    name: 'Move 5x / week',
    stat: '12-day streak',
    progress: 0.78,
    timeframe: 'This week',
    color: const Color(0xFF61E294),
    deadline: DateTime.now().add(const Duration(days: 6)),
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
  ),
  Goal(
    id: 'g2',
    name: 'Ship v1.0',
    stat: 'UI polish + QA next',
    progress: 0.65,
    timeframe: 'This month',
    color: const Color(0xFF7AE1FF),
    deadline: DateTime.now().add(const Duration(days: 20)),
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Goal(
    id: 'g3',
    name: 'Read 2 books',
    stat: '130 / 200 pages',
    progress: 0.62,
    timeframe: 'January',
    color: const Color(0xFFFF9F6E),
    deadline: DateTime.now().add(const Duration(days: 25)),
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
  ),
  Goal(
    id: 'g4',
    name: 'Budget reset',
    stat: 'Under cap by \$220',
    progress: 0.54,
    timeframe: 'Q1',
    color: const Color(0xFFB784FF),
    deadline: DateTime.now().add(const Duration(days: 45)),
    createdAt: DateTime.now().subtract(const Duration(days: 15)),
  ),
];
